# Generated by Django 2.2.4 on 2020-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='repository',
            field=models.URLField(blank=True, null=True),
        ),
    ]
