# Generated by Django 2.2.4 on 2020-06-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='desc_entity_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='desc_entity_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='desc_key_phrases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='title_entity_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='title_entity_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='title_key_phrases',
            field=models.TextField(blank=True),
        ),
    ]
