# Generated by Django 2.2.4 on 2020-06-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200613_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='desc_entity_name',
            new_name='text_analysis_params',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='desc_entity_type',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='desc_key_phrases',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='title_entity_name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='title_entity_type',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='title_key_phrases',
        ),
    ]
